// Subsets the embedded fonts and regenerates src/render/font-data.ts.
// Run via `npm run build:fonts` after changing faces or the glyph set.
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import subsetFont from 'subset-font';

const require = createRequire(import.meta.url);

// 16-bit CLI/TUI system: Silkscreen 700 carries the card titles (clean,
// unambiguous pixel caps — Pixelify's C read as G and its 5 as 8), VT323
// carries every class that can hold a number (0.40 avg advance, terminal
// digits that stay unambiguous at any size on this canvas).
const FACES = [
  {
    family: 'Silkscreen',
    weight: 700,
    file: '@fontsource/silkscreen/files/silkscreen-latin-700-normal.woff2',
  },
  { family: 'VT323', weight: 400, file: '@fontsource/vt323/files/vt323-latin-400-normal.woff2' },
];

// Printable ASCII + the typographic glyphs the cards actually render.
// (★ ↑ ✦ left with the designs that used them — and the pixel faces don't
// carry them anyway; a glyph absent from a subset renders as nothing.)
let glyphs = '';
for (let c = 0x20; c <= 0x7e; c++) glyphs += String.fromCharCode(c);
glyphs += '·—…–\u00a0';

const fonts = [];
for (const face of FACES) {
  const source = await readFile(require.resolve(face.file));
  const woff2 = await subsetFont(source, glyphs, { targetFormat: 'woff2' });
  const ttf = await subsetFont(source, glyphs, { targetFormat: 'sfnt' });
  fonts.push({
    family: face.family,
    weight: face.weight,
    woff2: woff2.toString('base64'),
    ttf: ttf.toString('base64'),
  });
  console.log(`${face.family} ${face.weight}: woff2 ${woff2.length} B, ttf ${ttf.length} B`);
}

const out = `// GENERATED by scripts/build-fonts.mjs — do not edit by hand.
export interface EmbeddedFont {
  family: string;
  weight: number;
  /** base64 woff2, for SVG @font-face data URIs */
  woff2: string;
  /** base64 ttf (sfnt), for resvg */
  ttf: string;
}

export const FONTS: EmbeddedFont[] = ${JSON.stringify(fonts, null, 2)};
`;

const target = new URL('../src/render/font-data.ts', import.meta.url);
await writeFile(target, out, 'utf8');
console.log(`Wrote ${target.pathname}`);
