// Subsets the embedded fonts and regenerates src/render/font-data.ts.
// Run via `npm run build:fonts` after changing faces or the glyph set.
import { readFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import subsetFont from 'subset-font';

const require = createRequire(import.meta.url);

const FACES = [
  { family: 'Inter', weight: 500, file: '@fontsource/inter/files/inter-latin-500-normal.woff2' },
  { family: 'Inter', weight: 700, file: '@fontsource/inter/files/inter-latin-700-normal.woff2' },
  {
    family: 'JetBrains Mono',
    weight: 600,
    file: '@fontsource/jetbrains-mono/files/jetbrains-mono-latin-600-normal.woff2',
  },
];

// Printable ASCII + the handful of typographic glyphs the cards use.
let glyphs = '';
for (let c = 0x20; c <= 0x7e; c++) glyphs += String.fromCharCode(c);
glyphs += '★·—…↑✦– ';

const fonts = [];
for (const face of FACES) {
  const source = await readFile(require.resolve(face.file));
  const woff2 = await subsetFont(source, glyphs, { targetFormat: 'woff2' });
  const ttf = await subsetFont(source, glyphs, { targetFormat: 'sfnt' });
  fonts.push({
    family: face.family,
    weight: face.weight,
    woff2: woff2.toString('base64'),
    ttf: ttf.toString('base64'),
  });
  console.log(`${face.family} ${face.weight}: woff2 ${woff2.length} B, ttf ${ttf.length} B`);
}

const out = `// GENERATED by scripts/build-fonts.mjs — do not edit by hand.
export interface EmbeddedFont {
  family: string;
  weight: number;
  /** base64 woff2, for SVG @font-face data URIs */
  woff2: string;
  /** base64 ttf (sfnt), for resvg */
  ttf: string;
}

export const FONTS: EmbeddedFont[] = ${JSON.stringify(fonts, null, 2)};
`;

const target = new URL('../src/render/font-data.ts', import.meta.url);
await writeFile(target, out, 'utf8');
console.log(`Wrote ${target.pathname}`);
